import type { Metadata } from "next";

import Header from "@/components/Header/Index";
import Footer from "@/components/Footer/Index";

import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Cercle Des Vignerons",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/simple_white_logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
