import type { Metadata } from "next";
import Head from "next/head";

import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Cercle Des Vignerons",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/simple_white_logo.svg",
  },
};

const personCDV = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Person",
      name: "Luc Lacombe",
      jobTitle: "Président Cercle Des Vignerons",
      telephone: "06 85 26 94 30",
      email: "cerclevigneron@aol.fr",
    },
    {
      "@type": "Person",
      name: "Yoan Lacombe",
      jobTitle: "Négociant en vins",
      email: "cerclevigneron@aol.fr",
    },
  ],
};

const preloadPicture = [
  { image: "/images/background_home.webp" },
  { image: "/images/bordeauxReg.webp" },
  { image: "/images/bourgogneReg.webp" },
  { image: "/images/champagneReg.webp" },
  { image: "/images/champagneReg.webp" },
  { image: "/images/rhoneReg.webp" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <Head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personCDV) }}
        />
        {preloadPicture.map((images) => (
          <link
            rel="preload"
            as="image"
            href={images.image}
            key={images.image}
          />
        ))}
      </Head>
      <body>{children}</body>
    </html>
  );
}
